export const APP_ROUTES = {
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  EDIT_PROFILE: '/profile/edit',
  ORGANIZATIONS: '/organizations',
  ORGANIZATION_DETAILS: '/organizations/:organizationId',
  ORGANIZATION_EDIT: '/organizations/:organizationId/edit',
  PEOPLE: '/people',
  PERSON_DETAILS: '/people/:personId',
  EVENTS: '/events',
  EVENT_DETAILS: '/events/:eventId',
  EDIT_EVENT: '/events/:eventId/edit',
  GUIDES: '/guides',
  GUIDE_DETAILS: '/guides/:guideId',
  HUBS: '/hubs',
  HUB_DETAILS: '/hubs/:hubId',
  CHAT: '/chat',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_TAGS: '/admin/tags',
  ADMIN_CHAT_CHANNELS: '/admin/chat-channels',
  AUTH: '/auth',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  CONTACT: '/contact',
  ABOUT: '/about',
  LANDING: '/',
  
  // Add the missing routes for tests and organizations
  TEST_REPORTS: '/admin/test-reports',
  ADMIN_TEST_RUN_DETAIL: '/admin/test-reports/:testRunId',
  ADMIN_TEST_DETAIL: '/admin/test-reports/:testRunId', // Alias for consistency
  MANAGE_ORGANIZATIONS: '/organizations/manage',
  CREATE_EVENT: '/events/create',
};
