
export const APP_ROUTES = {
  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  PROFILE_VIEW: '/profile/:profileId',
  PROFILE_EDIT: '/profile/edit',
  MANAGE_CONNECTIONS: '/profile/connections',
  ORGANIZATIONS: '/organizations',
  ORGANIZATION_DETAILS: '/organizations/:organizationId',
  ORGANIZATION_DETAIL: '/organizations/:organizationId', // Alias for consistency
  ORGANIZATION_EDIT: '/organizations/:organizationId/edit',
  CREATE_ORGANIZATION: '/organizations/create',
  MANAGE_ORGANIZATIONS: '/organizations/manage',
  PEOPLE: '/people',
  PERSON_DETAILS: '/people/:personId',
  EVENTS: '/events',
  EVENT_DETAILS: '/events/:eventId',
  EVENT_DETAIL: '/events/:eventId', // Alias for consistency
  EDIT_EVENT: '/events/:eventId/edit',
  EVENT_CREATE: '/events/create',
  CREATE_EVENT: '/events/create', // Alias for consistency
  FEED: '/feed',
  GUIDES: '/guides',
  GUIDE_DETAILS: '/guides/:guideId',
  HUBS: '/hubs',
  HUB_DETAILS: '/hubs/:hubId',
  CHAT: '/chat',
  CHAT_CHANNEL: '/chat/:channelId',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_TAGS: '/admin/tags',
  ADMIN_CHAT_CHANNELS: '/admin/chat-channels',
  ADMIN_TEST_REPORTS: '/admin/test-reports',
  ADMIN_TEST_RUN_DETAIL: '/admin/test-reports/:testRunId',
  ADMIN_TEST_DETAIL: '/admin/test-reports/:testRunId', // Alias for consistency
  ADMIN_DATA_GENERATOR: '/admin/data-generator',
  ADMIN_CHAT_CHANNEL_CREATE: '/admin/chat/channels/create',
  ADMIN_CHAT_CHANNEL_EDIT: '/admin/chat/channels/:channelId/edit',
  ADMIN_HUBS: '/admin/hubs',
  AUTH: '/auth',
  TERMS: '/terms',
  PRIVACY: '/privacy',
  CONTACT: '/contact',
  ABOUT: '/about',
  HOME: '/',
  LANDING: '/',
  COMMUNITY: '/community',
  COMMUNITY_GUIDE: '/community-guide',
  NOT_FOUND: '*'
};
