
name: API Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      # Production project (for test reporting and any integration tests)
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      
      # Production project URLs for test reporting (explicit variables)
      PROD_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      PROD_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      
      # Test project (for isolated test execution)
      TEST_SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL }}
      TEST_SUPABASE_ANON_KEY: ${{ secrets.TEST_SUPABASE_ANON_KEY }}
      TEST_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.TEST_SUPABASE_SERVICE_ROLE_KEY }}
      
      # Other variables
      TEST_REPORTING_API_KEY: ${{ secrets.TEST_REPORTING_API_KEY }}
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_REF_NAME: ${{ github.ref_name }}
      APP_URL: 'https://app.chosen.dev'
      NODE_ENV: 'test'

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Make test script executable
        run: chmod +x run-tests.cjs

      - name: Print dual connection environment info
        run: |
          echo "=== DUAL CONNECTION ARCHITECTURE ==="
          echo "PROD PROJECT (for reporting):"
          echo "  - PROD_SUPABASE_URL: ${{ secrets.SUPABASE_URL && '[SET]' || '[NOT SET]' }}"
          echo "  - PROD_SUPABASE_ANON_KEY LENGTH: ${#SUPABASE_ANON_KEY}"
          echo ""
          echo "TEST PROJECT (for execution):"
          echo "  - TEST_SUPABASE_URL: ${{ secrets.TEST_SUPABASE_URL && '[SET]' || '[NOT SET]' }}"
          echo "  - TEST_SUPABASE_ANON_KEY LENGTH: ${#TEST_SUPABASE_ANON_KEY}"
          echo "  - TEST SERVICE ROLE KEY LENGTH: ${#TEST_SUPABASE_SERVICE_ROLE_KEY}"
          echo ""
          echo "Results will be visible in production admin interface"

      - name: Run tests with dual connection
        run: ./run-tests.cjs
